services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: inventory-service
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - 3307:3306
        volumes:
            - mysql:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 7778:8080
volumes:
    mysql:
